### ISSUE TITLE
This package has been privatized

### ISSUE THREAD

**Issue by NeoPrint3D** [IGassmann/remark-directive-rehype#1]
Cant use it having the same problem in react

**Comment by IGassmann** [comment]
@NeoPrint3D what do you mean by it has been privatized?

**Comment by NeoPrint3D** [comment]
I got my code working but when I try to download this package it says I don't have permission to download it

**Comment by IGassmann** [comment]
What package manager are you using? What is the exact error message you're getting?

I'm not able to reproduce it on my end. Would you be able to share some code for me to reproduce the error locally?

**Comment by NeoPrint3D** [comment]
Sorry I can't reproduce it thanks for the help though
